### ISSUE TITLE
Cloudwatch Plugin should report the absense of an error for statistical purposes

### ISSUE THREAD

**Issue by heneryville** [mediarain/voxa#11]
The CloudWatch plugin should send a 0 metric when a response causes no errors. This will help statistical measures. I think it'd be difficult to write some alarms against this metric w/o the 0 value.

Also, we should really think through the namespace for these cloudwatch events. "StateMachine" almost certainly doesn't make sense. That would cause all the skills running on the same environment to overwrite each other. We probably should use a dimension to differentiate between different skills. Speculatively, I wonder if we use just the right dimension and just the right namespace, we could get it to log under the Lambda function so that Caught Errors would appear right next to Errors and Invocations.

Finally. CloudWatch should expose on the request object a helper to let other spots in the skill log things to cloudwatch (e.g. successful order placements, or timedout/fake orders in Starbucks)

**Comment by armonge** [comment]
@cvaca7 this basically mean modifying this https://github.com/mediarain/voxa/blob/master/lib/plugins/cloud-watch.js and https://github.com/mediarain/voxa/blob/master/test/plugins/cloud-watch.spec.js

Will be a good chance for you to learn on unit testing with [mocha](https://mochajs.org/) and [chain](http://chaijs.com/api/bdd/)

Use the playground account for your tests

**Comment by armonge** [comment]
Here's the original Pull Request for the feature, https://github.com/mediarain/alexa-statemachine/pull/30/files

Notice that  if you make any user visible changes then you also need to update the documentation

**Comment by cvaca7** [comment]
Issue completed
