### ISSUE TITLE
Access user's location (Google Action)

### ISSUE THREAD

**Issue by BruceLampson** [mediarain/voxa#112]
We're currently working on implementing a PermissionsRequest in order to determine a departure location. We would like to be able to ask permission to the user to access his location.

**Comment by lvelasquezm** [comment]
Here's some documentation on how the Actions on Google SDK implements it

https://developers.google.com/actions/assistant/helpers#user_information
https://developers.google.com/actions/reference/rest/Shared.Types/Permission

**Comment by jgutix** [comment]
I think this is now addressed at: https://github.com/mediarain/voxa/pull/114, should this be closed @armonge ?
