### ISSUE TITLE
Voxa crashes with a poor error message if an unknown state is referenced

### ISSUE THREAD

**Issue by heneryville** [mediarain/voxa#45]
When I direct things to an undefined state, I get a crash with an error message that isn't very helpful. In the example below the unknown state is AddToList. I'd expect an error message about this not being a known state. Double points if you can propose states that it might have been, like git's command suggestions.

https://github.com/mediarain/voxa/blob/master/lib/StateMachine.js#L114

voxa onError TypeError: Cannot read property 'AddToList' of undefined +1ms
  voxa TypeError: Cannot read property 'AddToList' of undefined
  voxa     at StateMachine.runCurrentState (/Users/mitchellharris/src/alexa/lists/node_modules/voxa/lib/StateMachine.js:114:34)
  voxa     at Promise.mapSeries.then (/Users/mitchellharris/src/alexa/lists/node_modules/voxa/lib/StateMachine.js:75:26)
  voxa     at tryCatcher (/Users/mitchellharris/src/alexa/lists/node_modules/bluebird/js/release/util.js:16:23)
  voxa     at Promise._settlePromiseFromHandler (/Users/mitchellharris/src/alexa/lists/node_modules/bluebird/js/release/promise.js:512:31)
  voxa     at Promise._settlePromise (/Users/mitchellharris/src/alexa/lists/node_modules/bluebird/js/release/promise.js:569:18)
  voxa     at Promise._settlePromiseCtx (/Users/mitchellharris/src/alexa/lists/node_modules/bluebird/js/release/promise.js:606:10)
  voxa     at Async._drainQueue (/Users/mitchellharris/src/alexa/lists/node_modules/bluebird/js/release/async.js:138:12)
  voxa     at Async._drainQueues (/Users/mitchellharris/src/alexa/lists/node_modules/bluebird/js/release/async.js:143:10)
  voxa     at Immediate.Async.drainQueues (/Users/mitchellharris/src/alexa/lists/node_modules/bluebird/js/release/async.js:17:14)
  voxa     at runCallback (timers.js:637:20)
  voxa     at tryOnImmediate (timers.js:610:5)
  voxa     at processImmediate [as _immediateCallback] (timers.js:582:5) +0ms

**Comment by heneryville** [comment]
This error message occurs only when the state is being picked up AFTER a request resumption from Alexa, not on internal transitions.

**Comment by rmberrios** [comment]
Solved in PR #37
