### ISSUE TITLE
Ask directive points to an object

### ISSUE THREAD

**Issue by heneryville** [mediarain/voxa#92]
In order to make the response editor in Command Center more efficient, we'll need to have the Ask directive work with an object, rather than an individual string. The object should be:
```
{
   "ssml": "This is what will be said",
   "reprompt": "This is the reprompt"
}
```
The key that holds the content should accept any of the following:
* ssml
* ask
* content
* say

**Comment by armonge** [comment]
Ask directive can now point to a view that renders a string or an object with `ask` and `reprompt` keys
